[TASK] Document new location of this file
TYPO3-Documentation/DocsTypo3Org-Homepage pull request #238
Opened 2024-05-27 10:50 UTC by garvinhicking

It has been moved some time ago: https://github.com/TYPO3GmbH/site-intercept/blob/develop/legacy_hook/ajaxversions.php

(Got this info from Andi)

2024-05-27 10:50 UTC, garvinhicking commented on WebRootResources/services/VersionMatcher.php
> +// Currently served via: https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/blob/main/.github/workflows/docshome.yml
```suggestion
// Currently served via: https://github.com/TYPO3GmbH/site-intercept/blob/develop/legacy_hook/ajaxversions.php
```

2024-05-27 10:50 UTC, garvinhicking commented on WebRootResources/services/VersionMatcher.php
> +// Currently served via: https://github.com/TYPO3-Documentation/DocsTypo3Org-Homepage/blob/main/.github/workflows/docshome.yml
```suggestion
// Currently served via: https://github.com/TYPO3GmbH/site-intercept/blob/develop/legacy_hook/ajaxversions.php
```

2024-05-28 20:07 UTC, froemken requested changes
If you have an answer for me, I will approve that.

2024-05-28 20:49 UTC, linawolf commented
@froemken what is the question?

2024-05-29 05:12 UTC, garvinhicking commented on WebRootResources/services/VersionMatcher.php
> +?>
```suggestion

```

2024-05-29 05:13 UTC, garvinhicking commented
I removed the file! Didn't see a comment of yours - note however, this file does not get deployed anywhere and is not executed. It's just legacy archive here.

2024-05-29 08:38 UTC, froemken approved these changes

2024-05-29 19:21 UTC, merged